### ISSUE TITLE
Don't redirect stderr

### ISSUE THREAD

**Issue by pauldotknopf** [adamralph/simple-exec#48]
Use of stderr by application is not standardised and does not necessarily contain only information which is appropriate for an exception message. Sometimes, visibility of stderr during execution is desirable, to view progress, or to view test failures as they happen. With this change, stderr is no longer redirected, leaving the default, or configured behaviour, in place, which is usually to print to the console. The exception message when a command fails will no longer include the contents of stderr. It will include only the process exit code.

<details>
<summary>
Original description
</summary>
Many commands contain long-winded information on stderr. Sometimes it is informative (exit code 0), sometimes it is an actual error.

Capturing and throwing stderr makes sense when using SimpleExec within a library/application, but not within the context of Bullseye and build scripts. It is best to let the stdout/stderr do it's thing, unabated, and just throw an exception if exit code is non-zero.
</details>

**Comment by adamralph** [comment]
@pauldotknopf can you explain more? Why is capturing stderr not appropriate in a build script?

**Comment by pauldotknopf** [comment]
The biggest example that comes to my mind is docker.

Running ```docker run ubuntu bash -c "echo test"``` will use stderr for layer progress, warnings, info, etc, while stdout is strictly for the command being executed.

If the layer doesn't get pulled (network error, invalid etc, etc), the stderr output get's throw into a .NET exception that is just gibberish, considering ```docker``` doesn't just output text, it moves the console cursor progress indicators.

This makes debugging build issues difficult, since the build logs will be unreadable.

**Comment by adamralph** [comment]
@pauldotknopf OK, I see what you mean.

Now that I think about it, I had a niggling feeling that putting stderr into the exception message would break down eventually, and here we are.

I think I agree with you, and we should remove the stderr capture. We also need consider how likely this change is to break any consumers, and whether it should come with a version bump to 3.0.

**Comment by adamralph** [comment]
I've raised a WIP PR while we think about it: https://github.com/adamralph/simple-exec/pull/49

**Comment by adamralph** [comment]
OK, I've thought about it and I've decided to proceed with the change, with a bump to 3.0 to be safe.

More evidence that the change is good:

## Before

![image](https://user-images.githubusercontent.com/677704/45800754-3101a180-bcf5-11e8-8ee1-ba83086db220.png)

## After

![image](https://user-images.githubusercontent.com/677704/45800773-3959dc80-bcf5-11e8-9191-8532f68ba259.png)

- The first message, about step 5 failing, goes to stderr, and so is suppressed in the first image, but shows in the second. This means that test failures are effectively buffered in the first example, and only shown at the end of the test run in the failed/skipped summary which is written to stdout.
- The red "Test run failed" line is missing from the output of the test target in the first example, since it goes to stderr. It only appears in the exception message.
- The exception message is included in the "Bullseye/test: Failed!" message, which means in the first example, that line is exploded to contain any other junk which is going to stderr.

@pauldotknopf in your original description of this issue, you said

> Capturing and throwing stderr makes sense when using SimpleExec within a library/application, but not within the context of Bullseye and build scripts.

I'm not sure capturing and throwing stderr makes sense in _any_ scenario. I'm going to edit the description of the issue a little so that it makes more sense as part of the release notes for 3.0. I'll keep your original description for reference.

Thanks very much for raising this issue!
